export default {
  changed: ['数据模型已发生变化，请勿忘记执行模型保存', 'The data model has changed, don’t forget to save the model'],
  exportModel: ['导出模型', 'Export Model'],
  save: ['保存', 'Save'],
  publish: ['发布', 'Publish'],
  system: ['系统功能字段', 'System function field'],
  addField: ['新增【$0】字段', 'Add [$0] field'],
  editField: ['修改【$0】字段', 'Edit [$0] field'],
  name: ['展示名称', 'Name'],
  name_zh_cn: ['中文为空', 'Chinese empty'],
  name_en_us: ['英文为空', 'English empty'],
  namePlaceholder: ['请输入展示名称', 'Please enter display name'],
  nameRequire: ['当前展示名称不能为空', 'Current display name cannot be empty'],
  column: ['数据库字段名', 'Column'],
  columnPlaceholder: ['请输入数据库字段名', 'Please enter table column'],
  columnRequire: ['当前数据库字段名不能为空', 'Current table column cannot be empty'],
  columnDuplicated: ['当前数据库字段名已存在', 'Current table column already exists'],
  datatype: ['数据类型', 'Datatype'],
  description: ['描述', 'Description'],
  descriptionPlaceholder: ['请输入字段描述', 'Please enter table column description'],
  default: ['默认值', 'Default'],
  defaultPlaceholder: ['请输入默认值', 'Please enter default value'],
  required: ['是否必须', 'Required'],
  max: ['最大值', 'Max'],
  maxPlaceholder: ['请输入最大值', 'Please enter max value'],
  min: ['最小值', 'Min'],
  minPlaceholder: ['请输入最小值', 'Please enter min value'],
  isText: ['是否为多行', 'Text'],
  isHide: ['列表隐藏', 'List Hide'],
  isSort: ['设为排序字段', 'Sort'],
  limit: ['限制数量', 'Limit'],
  limitPlaceholder: ['请输入限制数量', 'Please enter limit value'],
  allowSort: ['可排序', 'Allow Sort'],
  enum: ['枚举元素', 'Enum'],
  multiple: ['允许多选', 'Multiple'],
  addEnum: ['新增枚举元素', 'New enumeration element'],
  enumLabel: ['枚举元素别名', 'Enumeration element alias'],
  enumValue: ['枚举元素值', 'Enumeration element value'],
  assoc: ['关联类型', 'Assoc Type'],
  assocKey: ['关联键', 'Assoc Key'],
  assocName: ['关联名', 'Assoc Name'],
  publishSuccess: ['发布成功', 'Publish Success'],
  publishError: ['发布失败', 'Publish Failed'],
  publishConfirm: ['发布确认，请确保当前模型已保存', 'Publish confirm, please make sure that the current schema has been saved'],
  remarkPlaceholder: ['请输入模型发布内容', 'Please enter the content of the schema']
};
