// Code generated by kessoku. DO NOT EDIT.

package bootstrap

import (
	"github.com/kainonly/ddnspod/app"
	"github.com/mazrean/kessoku"
)

func OkLetsGo() (*app.App, error) {
	var err error
	values, err := kessoku.Provide(LoadValues).Fn()()
	if err != nil {
		var zero *app.App
		return zero, err
	}
	var err0 error
	client, err0 := kessoku.Provide(UseDnspod).Fn()(values)
	if err0 != nil {
		var zero *app.App
		return zero, err0
	}
	app0 := kessoku.Provide(app.NewApp).Fn()(values, client)
	return app0, nil
}
