// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ddnspod/app"
	"ddnspod/common"
	"github.com/robfig/cron/v3"
)

// Injectors from wire.go:

func Schedule(value *common.Values) (*cron.Cron, error) {
	service := &app.Service{
		Values: value,
	}
	task := &app.Task{
		Service: service,
		Values:  value,
	}
	cronCron, err := app.New(value, service, task)
	if err != nil {
		return nil, err
	}
	return cronCron, nil
}
