// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ddnspod/bootstrap"
	"ddnspod/common"
	"ddnspod/schedule"
	"github.com/robfig/cron/v3"
)

// Injectors from wire.go:

func Schedule(value *common.Values) (*cron.Cron, error) {
	dnspod := bootstrap.UseDnspod(value)
	webhook := bootstrap.UseWebhook(value)
	task := &schedule.Task{
		Values:  value,
		Dnspod:  dnspod,
		Webhook: webhook,
	}
	cronCron, err := schedule.New(value, dnspod, task)
	if err != nil {
		return nil, err
	}
	return cronCron, nil
}
